### ISSUE TITLE
rpn_R_50_C4_1x.yaml

### ISSUE THREAD

**Issue by deepseek** [TannerGilbert/Microcontroller-Detection-with-Detectron2#1]
@TannerGilbert Thank you for your amazing work

In case i want to predict and visualize using `rpn_R_50_C4_1x.yaml`, release an `ipynb` to test that.

since `rpn_R_50_C4_1x` doesn't use `instances` , it uses `proposals` boxes type.
the visualization can be done by opencv

**Comment by TannerGilbert** [comment]
Thanks for the information. Just tried it with openCV and it works.
