### ISSUE TITLE
Error opening video stream or file

### ISSUE THREAD

**Issue by haneeshb** [TannerGilbert/Microcontroller-Detection-with-Detectron2#2]
**Error opening video stream or file**
I followed your code from "https://github.com/TannerGilbert/Microcontroller-Detection-with-Detectron2/blob/master/detect_from_webcam_or_video.py" 
after running this in colab notebook, it is giving error.

**Screenshots**
![image](https://user-images.githubusercontent.com/49804700/84822142-dae0a000-b039-11ea-8715-71644def5372.png)

**Desktop (please complete the following information):**
 - OS: [Windows-10]
 - Browser [chrome]
 - Version [83.0.4103.97]

Please help me to access webcam from colab notebook.

**Comment by haneeshb** [comment]
Actually I run the code "detect_from_webcam_or_video.py" in colab notebook.
I found that we cannot use webcam using cv2 in colab and javascript is doing pretty well with webcam in colab notebook.
request you to create javascript file on how to detect from webcam on micro controller detection repository.
Thanks in advance..

**Comment by TannerGilbert** [comment]
Sorry for not replying. Check out https://stackoverflow.com/questions/54389727/how-to-use-cap-cv2-videocapture0-in-google-colab for some tips on how to use a camera in Google Colab.
